# This is a Docker Compose configuration file using version 3.9 of the Compose file format.
# Version 3.9 is compatible with Docker Engine 19.03.0 and higher.
# It is used to define and manage multi-container Docker applications.
version: '3.9'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=ollama,localhost,127.0.0.1
    expose:
      - "8000"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - ollama
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
      - ollama
  
volumes:
  ollama: